[package]
name = "dietpi-dashboard"
version = "0.7.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = "fat"
strip = true

[dependencies]
axum = { version = "0.6.20", default-features = false, features = ["http1", "tokio", "json"] }
color-eyre = "0.6.2"
ephemeropt = "0.2.0"
flexible-hyper-server-tls = "0.1.1"
pretty-bytes-typed = { version = "0.1.1", features = ["serde"] }
serde = { version = "1.0.183", features = ["serde_derive"] }
sysinfo = { version = "0.29.7", default-features = false }
tokio = { version = "1.29.1", features = ["rt", "macros"] }
tsync-macro = "0.1.0"
vite-embed-axum = { git = "https://github.com/ravenclaw900/vite-embed", version = "0.1.0", features = ["prod"], optional = true }

[features]
frontend = ["dep:vite-embed-axum"]
dev = ["frontend", "vite-embed-axum/dev"]
