[workspace]
members = ["crates/sysdata", "crates/server", "crates/frontend", "crates/system_api", "crates/config", "crates/auth"]
resolver = "2"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"

[workspace.lints.rust]
rust_2018_idioms = "warn"

[profile.release]
panic = "abort"
lto = "fat"
strip = true
