[package]
name = "dietpi-dashboard"
version = "0.7.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = "fat"
strip = true

[dependencies]
axum = { version = "0.6.20", default-features = false, features = ["http1", "tokio"] }
color-eyre = "0.6.2"
ephemeropt = "0.2.0"
maud = { version = "0.25.0", features = ["axum"] }
sysinfo = { version = "0.29.7", default-features = false }
tokio = { version = "1.29.1", features = ["rt", "macros"] }
