[package]
name = "config"
version = "0.7.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
toml_edit = { version = "0.22.13", features = ["serde"] }
