[package]
name = "frontend"
version = "0.7.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.20", default-features = false }
maud = { version = "0.25.0", features = ["axum"] }
pretty-bytes-typed = "0.2.0"
sysdata = { version = "0.7.0", path = "../sysdata" }
tokio = { version = "1.34.0", features = ["sync"] }
