CONFIG_VERSION_DO_NOT_CHANGE = 1

# TCP network port
# - Default: 5252
port = {port}

# Maximum log level
# - Options: "off", "error", "warn", "info", "debug"
# - Default: "info"
log_level = {log_level}

# TLS for HTTPS
[tls]
# Enable HTTPS mode
# - Default: false
enable_tls = {enable_tls}
# Path to TLS certificate
cert_path = {cert_path}
# Path to TLS private key
key_path = {key_path}

# Password authentication
[auth]
# Enable password auth
# - Default: false
enable_auth = {enable_auth}
# Path to ED25519 private key
privkey_path = {privkey_path}
# Path to ED25519 public key
pubkey_path = {pubkey_path}
# SHA-512 hash of password
hash = {hash}
# Expiry time of login token in seconds
# - Default: 3600
expiry = {expiry}
