[package]
name = "hyper_ext"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
http-body-util = "0.1.2"
hyper.workspace = true
hyper-tungstenite = "0.14.0"
maud.workspace = true
serde.workspace = true
serde_urlencoded = "0.7.1"
tokio.workspace = true

[lints]
workspace = true
