[package]
name = "sysdata"
version = "0.7.0"
edition = "2021"

[dependencies]
ephemeropt = "0.2.2"
sysinfo = { version = "0.29.10", default-features = false }
tokio = { version = "1.34.0", default-features = false, features = ["rt", "sync"] }
