[package]
name = "server"
version = "0.7.0"
edition = "2021"

[[bin]]
name = "dietpi-dashboard"
path = "src/main.rs"

[dependencies]
axum = { version = "0.6.20", default-features = false, features = ["http1", "tokio"] }
frontend = { path = "../frontend" }
sysdata = { path = "../sysdata" }
system_api = { version = "0.7.0", path = "../system_api" }
tokio = { version = "1.34.0", features = ["rt", "macros"] }
